suites:
  - name: was_cluster
    driver:
      synced_folders:
        - ["~/sainsburys/identity/media", "/opt/ibm-media"]
      # network:
      #   - ["forwarded_port", {guest: 9043, host: 9043}]
      #   - ["forwarded_port", {guest: 9080, host: 9080}]
      #   - ["forwarded_port", {guest: 9081, host: 9081}]
      #   - ["forwarded_port", {guest: 80, host: 8888}]
    run_list:
      - recipe[websphere-test::was_cluster]
  - name: was_install
    driver:
      synced_folders:
        - ["~/sainsburys/identity/media", "/opt/ibm-media"]
      network:
        - ["forwarded_port", {guest: 9043, host: 9843}]
    run_list:
      - recipe[websphere-test::was_install]

  - name: was_webserver
    driver:
      synced_folders:
        - ["~/sainsburys/identity/media", "/opt/ibm-media"]
      network:
        - ["forwarded_port", {guest: 9043, host: 9943}]
    run_list:
      - recipe[websphere-test::was_webserver]

  - name: ibm_certs
    driver:
      synced_folders:
        - ["~/sainsburys/identity/media", "/opt/ibm-media"]
    run_list:
      - recipe[websphere-test::ibm_certs]

  - name: was_jms
    driver:
      synced_folders:
        - ["~/sainsburys/identity/media", "/opt/ibm-media"]
    run_list:
      - recipe[websphere-test::was_jms]
