driver:
  name: dokken
  require_chef_omnibus: latest
  privileged: true

verifier:
  root_path: '/opt/verifier'
  sudo: false

transport:
  name: dokken

provisioner:
  name: dokken
  attributes:
    websphere-test:
      passport_advantage:
        user: <%= ENV['PASSPORTADV_USER'] %>
        password: <%= ENV['PASSPORTADV_PW'] %>
      aws:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key_secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        region: <%= ENV['AWS_REGION'] %>
platforms:
- name: centos-6
  driver:
    image: centos:6
- name: centos-7
  driver:
    image: centos:7

suites:
  - name: was-cluster
    run_list:
      - recipe[websphere-test::was_cluster]
