driver:
  name: vagrant
  #require_chef_omnibus: latest
  customize:
    memory: 4096

provisioner:
  name: chef_zero
  attributes:
    websphere-test:
      passport_advantage:
        user: <%= ENV['PASSPORTADV_USER'] %>
        password: <%= ENV['PASSPORTADV_PW'] %>
      aws:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key_secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        region: <%= ENV['AWS_REGION'] %>
platforms:
  - name: opscode-centos-6.7

suites:
  - name: was_cluster
    run_list:
      - recipe[websphere-test::was_cluster]
  - name: was_app_server
    run_list:
      - recipe[websphere-test::was_app_server]
  - name: ibm_certs
    run_list:
      - recipe[websphere-test::ibm_certs]
  - name: was_jms
    run_list:
      - recipe[websphere-test::was_jms]
