---
driver:
  name: ec2
  region: eu-west-1
  aws_ssh_key_id: lmunro-js-identity-aws
  instance_type: t2.large
  shared_credentials_profile: js-identity
  # temp vpc
  security_group_ids: [ sg-abfe3ecc ]
  subnet_id: subnet-40706619
  associate_public_ip: true
  iam_profile_name: id-chef
  #interface: private
  tags:
    Owner: lachlan.munro
    Email: lachlan.munro@sainsburys.co.uk
    Description: ibm-websphere cookbook test kitchen instance
    Name: test-kitchen-ibm-websphere
    Costcentre: Identity
    Project: Identity
    Environment: dev

platforms:
  - name: centos-6
    driver:
      image_id: ami-7b9f0e08 # resized version of centos base ami-edb9069e
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 40
            delete_on_termination: true

transport:
  ssh_key: ~/.ssh/lmunro-js-identity-aws.pem
  name: sftp

suites:
  - name: was_cluster
    run_list:
      - recipe[websphere-test::was_cluster]
  - name: ibm_certs
    run_list:
      - recipe[websphere-test::ibm_certs]
  - name: was_jms_env
    run_list:
      - recipe[websphere-test::was_jms]
  - name: was_app_server
    run_list:
      - recipe[websphere-test::was_app_server]
