source 'https://rubygems.org'

group :ci, :test, :development do
  gem 'aws-eventstream'
  gem 'aws-partitions'
  gem 'aws-sigv4'
  gem 'aws-sdk-autoscaling'
  gem 'aws-sdk-cloudformation'
  gem 'aws-sdk-cloudwatch'
  gem 'aws-sdk-core'
  gem 'aws-sdk-dynamodb'
  gem 'aws-sdk-ec2'
  gem 'aws-sdk-elasticloadbalancing'
  gem 'aws-sdk-iam'
  gem 'aws-sdk-kinesis'
  gem 'aws-sdk-kms'
  gem 'aws-sdk-rds'
  gem 'aws-sdk-route53'
  gem 'aws-sdk-s3'
  gem 'aws-sdk-ssm'
  gem 'chefspec'
  gem 'cookstyle'
  gem 'kitchen-dokken'
  gem 'kitchen-inspec'
end
